### PR TITLE
Basic Login - feature

### PR DESCRIPTION
**Pull request by philwilliammee**
Addresses #7   [Basic login #7](https://github.com/CU-CommunityApps/cd-son/issues/7)

This functions very similar to CUWEBAUTH currently used on all media3 sites.

Before each request authentication is checked if user is not authenticated they will automatically be directed to saml login. If they pass saml login they are authenticated into the site. If the user does not exist they will be logged in as "authenticated" user.

- When I log in successfully I go to the Home page
-  Home page displays the logged in user's ID
image

also if you go to welcome page you will see all details returned by simplesamlphp
image

readme was also updated addresses #1

### CODE REVIEW

**Comment by philwilliammee** [comment]
commit d3e9f00 basic son

Addresses issue #8 

basic son form:
image

Saving the new SON successfully returns me to the home page and shows success status
image

Saves to database:
image

both server side and client side validation added.

**Comment by woodseowl** [comment]
@philwilliammee I'm taking a quick look and I can see that I cannot just run this locally and test, so I'm going to have to review it next week. That said, I have a couple process requests so that you can proceed without me blocking you...

- Can we use issue-based branches for each issue? This PR has three issues related to it now (#1, #7, #8), so the scope of review coverage to call it done is getting large for me as a reviewer. 
- Potential convention for that: [ID]-[readable-name]. For example `7-login`, `8-basic-son`
- Each PR then would be set up to close a given issue
- It's okay if we have branches that are branched off other branches if you just need to keep things moving. But keeping them separate branches lets the testing/review occur in units.

So, for me right now, as a complete neophyte with Laravel, I would love to have a branch just for the updates to the readme so that I could stand up a non-simplesaml version of the site and can agree that those directions get me to the Welcome page.

If this sounds like nonsense or a ton of extra work, let's talk. I don't want to make this heavy, but I also want to be able to keep up and help out.

**Comment by philwilliammee** [comment]
Hmm, You should be able to get it up and running locally pretty easily. What issues are you having? If you want I can put the protected files in box then it should start up quick.

master should work as non simplesaml.

Yeah, I'll try that naming convention for branches and pull requests. I'm just worried about dependencies and merge conflicts. A lot of these steps build on each other, and touch some of the same files.

If you have time tomorrow maybe we can take a pause and review some stuff together.

**Comment by philwilliammee** [comment]
OK I'll close this pull request and start over. I'll also add a changelog file, and do a better job of commenting. I really appreciate the feedback, I haven't work with a team very much its usually just me working in isolation :(

**Pull request closed without merging**
